import 'package:intl/intl.dart';
import 'package:supabase_flutter/supabase_flutter.dart';


//-----------MANUAL--------------------------
// class TransactionService {
//   /// Calculate change given total and cash
//   double calculateChange(double total, double cash) {
//     return cash - total;
//   }

//   /// Get current timestamp formatted as MM-dd-yyyy HH:mm:ss
//   String getCurrentTimestamp() {
//     DateTime now = DateTime.now();
//     return DateFormat('MM-dd-yyyy HH:mm:ss').format(now);
//   }

//   /// Validate if cash is enough
//   bool isCashSufficient(double total, double cash) {
//     return cash >= total;
//   }
// }



//-------------SUPABASE-----------------------

class TransactionService {
  final SupabaseClient supabase = Supabase.instance.client;

  /// Calculate change given total and cash
  double calculateChange(double total, double cash) {
    return cash - total;
  }

  /// Get current timestamp formatted as MM-dd-yyyy HH:mm:ss
  String getCurrentTimestamp() {
    DateTime now = DateTime.now();
    return DateFormat('MM-dd-yyyy HH:mm:ss').format(now);
  }

  /// Validate if cash is enough
  bool isCashSufficient(double total, double cash) {
    return cash >= total;
  }

  /// Save transaction to Supabase
  /// Returns the inserted transaction ID
  Future<int> saveTransaction({
    required double total,
    required double cash,
    required double change,
  }) async {
    final response = await supabase
        .from('transactions')
        .insert({
          'total': total,
          'cash': cash,
          'change': change,
          // 'created_at' is auto-generated by Supabase
        })
        .select()
        .single(); // return inserted row

    return response['id'];
  }
}

